// src/shared/themes/presets.ts
import type { Appearance, ConcreteThemeId, TerminalThemeColors, ThemePreset, UiTokens } from './types'
import { darken, lighten, mix, rgba } from './colorUtils'

// Derive a full UiTokens set from a terminal color palette + appearance hint.
// The goal: a consistent, readable look per theme without hand-authoring 50 values each.
// Individual presets can spread() over this to override specific tokens.
function deriveUiTokens(term: TerminalThemeColors, appearance: Appearance): UiTokens {
  const bg = term.background
  const fg = term.foreground
  const accent = term.blue || term.cyan || fg
  const isDark = appearance === 'dark'

  // Background ladder — each step slightly away from the base toward the opposite pole.
  const step = (amount: number) => (isDark ? lighten(bg, amount) : darken(bg, amount))

  const bgSecondary = step(0.04)
  const bgTertiary = step(0.08)
  const bgQuaternary = step(0.16)
  const bgQuinary = step(0.1)
  const bgSenary = step(0.06)
  const bgSeptenary = step(0.05)
  const bgOctonary = step(0.18)
  const bgNovenary = step(0.22)
  const bgSwitch = step(0.06)

  const textPrimary = fg
  const textSecondary = mix(fg, bg, 0.2)
  const textTertiary = mix(fg, bg, 0.45)
  const textQuaternary = mix(fg, bg, 0.55)
  const textQuinary = mix(fg, bg, 0.65)
  const textSenary = mix(fg, bg, 0.75)
  const textSeptenary = mix(fg, bg, 0.85)

  const borderBase = isDark ? step(0.1) : step(0.08)
  const borderLight = isDark ? step(0.16) : step(0.12)

  const hoverRgba = isDark ? 'rgba(255, 255, 255, 0.1)' : 'rgba(15, 23, 42, 0.06)'
  const activeRgba = isDark ? 'rgba(255, 255, 255, 0.15)' : 'rgba(15, 23, 42, 0.1)'
  const watermark = isDark ? 'rgba(255, 255, 255, 0.05)' : 'rgba(15, 23, 42, 0.03)'

  const boxShadow = isDark
    ? '0 4px 6px rgba(0, 0, 0, 0.3), 0 2px 4px rgba(0, 0, 0, 0.2)'
    : '0 1px 3px rgba(0, 0, 0, 0.1), 0 1px 2px rgba(0, 0, 0, 0.06)'
  const cardShadow = boxShadow

  return {
    '--bg-color': bg,
    '--bg-color-secondary': bgSecondary,
    '--bg-color-tertiary': bgTertiary,
    '--bg-color-quaternary': bgQuaternary,
    '--bg-color-quinary': bgQuinary,
    '--bg-color-senary': bgSenary,
    '--bg-color-septenary': bgSeptenary,
    '--bg-color-octonary': bgOctonary,
    '--bg-color-novenary': bgNovenary,
    '--bg-color-suggestion': bgSecondary,
    '--bg-color-vim-editor': bgSecondary,
    '--bg-color-switch': bgSwitch,
    '--bg-color-default': bgQuaternary,

    '--text-color': textPrimary,
    '--text-color-secondary': textSecondary,
    '--text-color-secondary-light': textSecondary,
    '--text-color-tertiary': textTertiary,
    '--text-color-quaternary': textQuaternary,
    '--text-color-quinary': textQuinary,
    '--text-color-senary': textSenary,
    '--text-color-septenary': textSeptenary,

    '--border-color': borderBase,
    '--border-color-light': borderLight,
    '--splitter-color': borderBase,

    '--hover-bg-color': hoverRgba,
    '--active-bg-color': activeRgba,
    '--watermark-color': watermark,

    '--icon-filter': isDark ? 'brightness(0) invert(1)' : 'brightness(0) saturate(100%)',
    '--globalInput-bg-color': bgQuinary,
    '--button-bg-color': accent,
    '--box-shadow': boxShadow,
    '--button-default-bg-color': bgQuaternary,

    '--input-number-bg': bgQuinary,
    '--input-number-hover-bg': bgQuaternary,
    '--select-bg': bgQuinary,
    '--select-hover-bg': bgQuaternary,
    '--select-border': borderLight,

    '--card-bg': bgSenary,
    '--card-border': bgQuaternary,
    '--card-shadow': cardShadow,
    '--command-output-bg': bgSecondary,
    '--input-focus-border': lighten(accent, 0.1),
    '--input-focus-shadow': `0 0 0 3px ${rgba(accent, 0.2)}`,
    '--button-hover-bg': lighten(accent, 0.1),
    '--button-active-bg': darken(accent, 0.15),
    '--success-color': '#10b981',
    '--warning-color': '#f59e0b',
    '--error-color': '#ef4444',
    '--info-color': accent,

    '--scrollbar-track-color': bgSecondary,
    '--scrollbar-thumb-color': isDark ? step(0.2) : step(0.18),
    '--scrollbar-thumb-hover-color': isDark ? step(0.3) : step(0.28)
  }
}

function preset(
  id: ConcreteThemeId,
  name: string,
  appearance: Appearance,
  term: TerminalThemeColors,
  ui: UiTokens,
  titleBar: { color: string; symbolColor: string }
): ThemePreset {
  return {
    id,
    name,
    appearance,
    uiTokens: ui,
    terminalTheme: term,
    titleBarOverlay: { color: titleBar.color, symbolColor: titleBar.symbolColor, height: 27 }
  }
}

function withUiOverrides(term: TerminalThemeColors, appearance: Appearance, overrides: Partial<UiTokens>): UiTokens {
  return {
    ...deriveUiTokens(term, appearance),
    ...overrides
  }
}

// ---------------------------------------------------------------------------
// Terminal palettes
// ---------------------------------------------------------------------------

const DARK_TERM: TerminalThemeColors = {
  background: '#141414',
  foreground: '#f5f5f5',
  cursor: '#f5f5f5',
  cursorAccent: '#141414',
  selectionBackground: '#2a3f54',
  black: '#000000',
  red: '#cc0000',
  green: '#00aa00',
  yellow: '#aa8800',
  blue: '#0066cc',
  magenta: '#aa00aa',
  cyan: '#00aaaa',
  white: '#dddddd',
  brightBlack: '#555555',
  brightRed: '#ff5555',
  brightGreen: '#55ff55',
  brightYellow: '#ffff55',
  brightBlue: '#5555ff',
  brightMagenta: '#ff55ff',
  brightCyan: '#55ffff',
  brightWhite: '#ffffff'
}

const LIGHT_TERM: TerminalThemeColors = {
  background: '#ffffff',
  foreground: '#141414',
  cursor: '#141414',
  cursorAccent: '#ffffff',
  selectionBackground: '#cce4ff',
  black: '#000000',
  red: '#cc0000',
  green: '#00aa00',
  yellow: '#aa8800',
  blue: '#0066cc',
  magenta: '#aa00aa',
  cyan: '#00aaaa',
  white: '#dddddd',
  brightBlack: '#555555',
  brightRed: '#ff5555',
  brightGreen: '#55ff55',
  brightYellow: '#ffff55',
  brightBlue: '#5555ff',
  brightMagenta: '#ff55ff',
  brightCyan: '#55ffff',
  brightWhite: '#ffffff'
}

const TERMIUS_DARK_TERM: TerminalThemeColors = {
  background: '#111417',
  foreground: '#D9DBDE',
  cursor: '#AFC6E3',
  cursorAccent: '#111417',
  selectionBackground: '#2A3F54',
  black: '#1B1D1F',
  red: '#F36E6E',
  green: '#7FC06E',
  yellow: '#EEBE6C',
  blue: '#6C9CF4',
  magenta: '#C583E0',
  cyan: '#6CC0D4',
  white: '#D9DBDE',
  brightBlack: '#5B6268',
  brightRed: '#FF8888',
  brightGreen: '#A0D683',
  brightYellow: '#FFD080',
  brightBlue: '#8EB4FF',
  brightMagenta: '#DDA0DD',
  brightCyan: '#8FDCEF',
  brightWhite: '#FFFFFF'
}

const TERMIUS_LIGHT_TERM: TerminalThemeColors = {
  background: '#FFFFFF',
  foreground: '#2A2F33',
  cursor: '#2A6FDB',
  cursorAccent: '#FFFFFF',
  selectionBackground: '#CCE4FF',
  black: '#24292E',
  red: '#D03035',
  green: '#22863A',
  yellow: '#B08800',
  blue: '#0366D6',
  magenta: '#8A3CB5',
  cyan: '#1184A3',
  white: '#E1E4E8',
  brightBlack: '#6A737D',
  brightRed: '#CB2431',
  brightGreen: '#28A745',
  brightYellow: '#DBAB09',
  brightBlue: '#2188FF',
  brightMagenta: '#B392F0',
  brightCyan: '#34D0E1',
  brightWhite: '#FAFBFC'
}

const FLEXOKI_DARK_TERM: TerminalThemeColors = {
  background: '#100F0F',
  foreground: '#CECDC3',
  cursor: '#CECDC3',
  cursorAccent: '#100F0F',
  selectionBackground: '#282726',
  black: '#1C1B1A',
  red: '#AF3029',
  green: '#66800B',
  yellow: '#AD8301',
  blue: '#205EA6',
  magenta: '#A02F6F',
  cyan: '#24837B',
  white: '#878580',
  brightBlack: '#575653',
  brightRed: '#D14D41',
  brightGreen: '#879A39',
  brightYellow: '#D0A215',
  brightBlue: '#4385BE',
  brightMagenta: '#CE5D97',
  brightCyan: '#3AA99F',
  brightWhite: '#CECDC3'
}

const FLEXOKI_LIGHT_TERM: TerminalThemeColors = {
  background: '#FFFCF0',
  foreground: '#100F0F',
  cursor: '#100F0F',
  cursorAccent: '#FFFCF0',
  selectionBackground: '#DAD8CE',
  black: '#100F0F',
  red: '#AF3029',
  green: '#66800B',
  yellow: '#AD8301',
  blue: '#205EA6',
  magenta: '#A02F6F',
  cyan: '#24837B',
  white: '#6F6E69',
  brightBlack: '#B7B5AC',
  brightRed: '#D14D41',
  brightGreen: '#879A39',
  brightYellow: '#D0A215',
  brightBlue: '#4385BE',
  brightMagenta: '#CE5D97',
  brightCyan: '#3AA99F',
  brightWhite: '#1C1B1A'
}

const KANAGAWA_WAVE_TERM: TerminalThemeColors = {
  background: '#1F1F28',
  foreground: '#DCD7BA',
  cursor: '#C8C093',
  cursorAccent: '#1F1F28',
  selectionBackground: '#2D4F67',
  black: '#090618',
  red: '#C34043',
  green: '#76946A',
  yellow: '#C0A36E',
  blue: '#7E9CD8',
  magenta: '#957FB8',
  cyan: '#6A9589',
  white: '#C8C093',
  brightBlack: '#727169',
  brightRed: '#E82424',
  brightGreen: '#98BB6C',
  brightYellow: '#E6C384',
  brightBlue: '#7FB4CA',
  brightMagenta: '#938AA9',
  brightCyan: '#7AA89F',
  brightWhite: '#DCD7BA'
}

const KANAGAWA_DRAGON_TERM: TerminalThemeColors = {
  background: '#181616',
  foreground: '#C5C9C5',
  cursor: '#C5C9C5',
  cursorAccent: '#181616',
  selectionBackground: '#2D4F67',
  black: '#0D0C0C',
  red: '#C4746E',
  green: '#8A9A7B',
  yellow: '#C4B28A',
  blue: '#8BA4B0',
  magenta: '#A292A3',
  cyan: '#8EA4A2',
  white: '#C8C093',
  brightBlack: '#A6A69C',
  brightRed: '#E46876',
  brightGreen: '#87A987',
  brightYellow: '#E6C384',
  brightBlue: '#7FB4CA',
  brightMagenta: '#938AA9',
  brightCyan: '#7AA89F',
  brightWhite: '#C5C9C5'
}

const KANAGAWA_LOTUS_TERM: TerminalThemeColors = {
  background: '#F2ECBC',
  foreground: '#545464',
  cursor: '#43436C',
  cursorAccent: '#F2ECBC',
  selectionBackground: '#C9CBD1',
  black: '#1F1F28',
  red: '#C84053',
  green: '#6F894E',
  yellow: '#77713F',
  blue: '#4D699B',
  magenta: '#B35B79',
  cyan: '#597B75',
  white: '#545464',
  brightBlack: '#8A8980',
  brightRed: '#D7474B',
  brightGreen: '#6E915F',
  brightYellow: '#836F4A',
  brightBlue: '#6693BF',
  brightMagenta: '#624C83',
  brightCyan: '#5E857A',
  brightWhite: '#43436C'
}

const HACKER_BLUE_TERM: TerminalThemeColors = {
  background: '#000000',
  foreground: '#4D9FFF',
  cursor: '#4D9FFF',
  cursorAccent: '#000000',
  selectionBackground: '#003366',
  black: '#000000',
  red: '#2A6FC7',
  green: '#1E90FF',
  yellow: '#4FA8FF',
  blue: '#0066CC',
  magenta: '#5AA9FF',
  cyan: '#4DC3FF',
  white: '#A6CEFF',
  brightBlack: '#2A4F7C',
  brightRed: '#4D9FFF',
  brightGreen: '#66B2FF',
  brightYellow: '#80BFFF',
  brightBlue: '#3399FF',
  brightMagenta: '#99CCFF',
  brightCyan: '#B3D9FF',
  brightWhite: '#E6F2FF'
}

const HACKER_GREEN_TERM: TerminalThemeColors = {
  background: '#000000',
  foreground: '#00FF00',
  cursor: '#00FF00',
  cursorAccent: '#000000',
  selectionBackground: '#003300',
  black: '#000000',
  red: '#008F11',
  green: '#00AA00',
  yellow: '#00CC00',
  blue: '#007700',
  magenta: '#009900',
  cyan: '#00BB88',
  white: '#00FF00',
  brightBlack: '#006600',
  brightRed: '#00C000',
  brightGreen: '#00FF41',
  brightYellow: '#66FF66',
  brightBlue: '#00AA55',
  brightMagenta: '#33FF33',
  brightCyan: '#66FFCC',
  brightWhite: '#CCFFCC'
}

const DRACULA_NIGHT_TERM: TerminalThemeColors = {
  background: '#282A36',
  foreground: '#F8F8F2',
  cursor: '#F8F8F2',
  cursorAccent: '#282A36',
  selectionBackground: '#44475A',
  black: '#21222C',
  red: '#FF5555',
  green: '#50FA7B',
  yellow: '#F1FA8C',
  blue: '#BD93F9',
  magenta: '#FF79C6',
  cyan: '#8BE9FD',
  white: '#F8F8F2',
  brightBlack: '#6272A4',
  brightRed: '#FF6E6E',
  brightGreen: '#69FF94',
  brightYellow: '#FFFFA5',
  brightBlue: '#D6ACFF',
  brightMagenta: '#FF92DF',
  brightCyan: '#A4FFFF',
  brightWhite: '#FFFFFF'
}

const CATPPUCCIN_MOCHA_TERM: TerminalThemeColors = {
  background: '#1E1E2E',
  foreground: '#CDD6F4',
  cursor: '#F5E0DC',
  cursorAccent: '#1E1E2E',
  selectionBackground: '#45475A',
  black: '#45475A',
  red: '#F38BA8',
  green: '#A6E3A1',
  yellow: '#F9E2AF',
  blue: '#89B4FA',
  magenta: '#F5C2E7',
  cyan: '#94E2D5',
  white: '#BAC2DE',
  brightBlack: '#585B70',
  brightRed: '#F38BA8',
  brightGreen: '#A6E3A1',
  brightYellow: '#F9E2AF',
  brightBlue: '#89B4FA',
  brightMagenta: '#F5C2E7',
  brightCyan: '#94E2D5',
  brightWhite: '#A6ADC8'
}

const CATPPUCCIN_LATTE_TERM: TerminalThemeColors = {
  background: '#EFF1F5',
  foreground: '#4C4F69',
  cursor: '#DC8A78',
  cursorAccent: '#EFF1F5',
  selectionBackground: '#CCD0DA',
  black: '#5C5F77',
  red: '#D20F39',
  green: '#40A02B',
  yellow: '#DF8E1D',
  blue: '#1E66F5',
  magenta: '#EA76CB',
  cyan: '#179299',
  white: '#ACB0BE',
  brightBlack: '#6C6F85',
  brightRed: '#D20F39',
  brightGreen: '#40A02B',
  brightYellow: '#DF8E1D',
  brightBlue: '#1E66F5',
  brightMagenta: '#EA76CB',
  brightCyan: '#179299',
  brightWhite: '#BCC0CC'
}

const GRUVBOX_DARK_TERM: TerminalThemeColors = {
  background: '#282828',
  foreground: '#EBDBB2',
  cursor: '#EBDBB2',
  cursorAccent: '#282828',
  selectionBackground: '#504945',
  black: '#282828',
  red: '#CC241D',
  green: '#98971A',
  yellow: '#D79921',
  blue: '#458588',
  magenta: '#B16286',
  cyan: '#689D6A',
  white: '#A89984',
  brightBlack: '#928374',
  brightRed: '#FB4934',
  brightGreen: '#B8BB26',
  brightYellow: '#FABD2F',
  brightBlue: '#83A598',
  brightMagenta: '#D3869B',
  brightCyan: '#8EC07C',
  brightWhite: '#FBF1C7'
}

const NORD_FROST_TERM: TerminalThemeColors = {
  background: '#2E3440',
  foreground: '#D8DEE9',
  cursor: '#D8DEE9',
  cursorAccent: '#2E3440',
  selectionBackground: '#434C5E',
  black: '#3B4252',
  red: '#BF616A',
  green: '#A3BE8C',
  yellow: '#EBCB8B',
  blue: '#81A1C1',
  magenta: '#B48EAD',
  cyan: '#88C0D0',
  white: '#E5E9F0',
  brightBlack: '#4C566A',
  brightRed: '#BF616A',
  brightGreen: '#A3BE8C',
  brightYellow: '#EBCB8B',
  brightBlue: '#81A1C1',
  brightMagenta: '#B48EAD',
  brightCyan: '#8FBCBB',
  brightWhite: '#ECEFF4'
}

// ---------------------------------------------------------------------------
// Legacy dark/light UiTokens — copied verbatim from theme.less to preserve
// the current look pixel-for-pixel. New themes use deriveUiTokens below.
// ---------------------------------------------------------------------------

const LEGACY_DARK_UI: UiTokens = {
  '--bg-color': '#141414',
  '--bg-color-secondary': '#1e1e1e',
  '--bg-color-tertiary': '#252525',
  '--bg-color-quaternary': '#3c3c3c',
  '--bg-color-quinary': '#2d2d30',
  '--bg-color-senary': '#252526',
  '--bg-color-septenary': '#1e1e1e',
  '--bg-color-octonary': '#3c3c3c',
  '--bg-color-novenary': '#464647',
  '--bg-color-suggestion': '#1e1e1e',
  '--bg-color-vim-editor': '#1e1e1e',
  '--bg-color-switch': '#2a2a2a',
  '--bg-color-default': '#464647',
  '--text-color': '#e0e0e0',
  '--text-color-secondary': '#cbd5e1',
  '--text-color-secondary-light': '#cbd5e1',
  '--text-color-tertiary': '#666666',
  '--text-color-quaternary': '#64748b',
  '--text-color-quinary': '#475569',
  '--text-color-senary': '#334155',
  '--text-color-septenary': '#1e293b',
  '--border-color': '#1d1d1d',
  '--border-color-light': '#464647',
  '--splitter-color': '#1d1d1d',
  '--hover-bg-color': 'rgba(255, 255, 255, 0.1)',
  '--active-bg-color': 'rgba(255, 255, 255, 0.15)',
  '--watermark-color': 'rgba(255, 255, 255, 0.05)',
  '--icon-filter': 'brightness(0) invert(1)',
  '--globalInput-bg-color': '#2d2d30',
  '--button-bg-color': '#3b82f6',
  '--box-shadow': '0 4px 6px rgba(0, 0, 0, 0.3), 0 2px 4px rgba(0, 0, 0, 0.2)',
  '--button-default-bg-color': '#3c3c3c',
  '--input-number-bg': '#2d2d30',
  '--input-number-hover-bg': '#3c3c3c',
  '--select-bg': '#2d2d30',
  '--select-hover-bg': '#3c3c3c',
  '--select-border': '#464647',
  '--card-bg': '#252526',
  '--card-border': '#3c3c3c',
  '--card-shadow': '0 4px 6px rgba(0, 0, 0, 0.3), 0 2px 4px rgba(0, 0, 0, 0.2)',
  '--command-output-bg': '#1e1e1e',
  '--input-focus-border': '#60a5fa',
  '--input-focus-shadow': '0 0 0 3px rgba(96, 165, 250, 0.2)',
  '--button-hover-bg': '#60a5fa',
  '--button-active-bg': '#2563eb',
  '--success-color': '#10b981',
  '--warning-color': '#f59e0b',
  '--error-color': '#ef4444',
  '--info-color': '#3b82f6',
  '--scrollbar-track-color': '#2d2d30',
  '--scrollbar-thumb-color': '#555555',
  '--scrollbar-thumb-hover-color': '#666666'
}

const LEGACY_LIGHT_UI: UiTokens = {
  '--bg-color': '#f3f3f3',
  '--bg-color-secondary': '#f5f5f5',
  '--bg-color-tertiary': '#f1f5f9',
  '--bg-color-quaternary': '#e2e8f0',
  '--bg-color-quinary': '#f8fafc',
  '--bg-color-senary': '#f1f5f9',
  '--bg-color-septenary': '#e0f2fe',
  '--bg-color-octonary': '#f8fafc',
  '--bg-color-novenary': '#f1f5f9',
  '--bg-color-suggestion': '#ecfdf5',
  '--bg-color-vim-editor': '#f8fafc',
  '--bg-color-switch': '#d9d9d9',
  '--bg-color-default': '#e2e8f0',
  '--text-color': '#0f172a',
  '--text-color-secondary': '#334155',
  '--text-color-secondary-light': '#64748b',
  '--text-color-tertiary': '#94a3b8',
  '--text-color-quaternary': '#cbd5e1',
  '--text-color-quinary': '#e2e8f0',
  '--text-color-senary': '#f1f5f9',
  '--text-color-septenary': '#f8fafc',
  '--border-color': '#e2e8f0',
  '--border-color-light': '#e5e7eb',
  '--splitter-color': '#e2e8f0',
  '--hover-bg-color': 'rgba(15, 23, 42, 0.06)',
  '--active-bg-color': 'rgba(15, 23, 42, 0.1)',
  '--watermark-color': 'rgba(15, 23, 42, 0.03)',
  '--icon-filter': 'brightness(0) saturate(100%)',
  '--globalInput-bg-color': '#f1f5f9',
  '--button-bg-color': '#3b82f6',
  '--box-shadow': '0 1px 3px rgba(0, 0, 0, 0.1), 0 1px 2px rgba(0, 0, 0, 0.06)',
  '--button-default-bg-color': '#f3f3f3',
  '--input-number-bg': '#f8fafc',
  '--input-number-hover-bg': '#f1f5f9',
  '--select-bg': '#f8fafc',
  '--select-hover-bg': '#f1f5f9',
  '--select-border': '#e2e8f0',
  '--card-bg': '#f3f3f3',
  '--card-border': '#e2e8f0',
  '--card-shadow': '0 1px 3px rgba(0, 0, 0, 0.1), 0 1px 2px rgba(0, 0, 0, 0.06)',
  '--command-output-bg': '#f5f5f5',
  '--input-focus-border': '#3b82f6',
  '--input-focus-shadow': '0 0 0 3px rgba(59, 130, 246, 0.1)',
  '--button-hover-bg': '#2563eb',
  '--button-active-bg': '#1d4ed8',
  '--success-color': '#10b981',
  '--warning-color': '#f59e0b',
  '--error-color': '#ef4444',
  '--info-color': '#3b82f6',
  '--scrollbar-track-color': '#f1f1f1',
  '--scrollbar-thumb-color': '#c1c1c1',
  '--scrollbar-thumb-hover-color': '#a1a1a1'
}

const TERMIUS_DARK_UI = withUiOverrides(TERMIUS_DARK_TERM, 'dark', {
  '--bg-color': '#101722',
  '--bg-color-secondary': '#16202c',
  '--bg-color-tertiary': '#1d2836',
  '--bg-color-quaternary': '#253244',
  '--bg-color-quinary': '#1d2937',
  '--bg-color-senary': '#18222e',
  '--bg-color-septenary': '#182431',
  '--bg-color-octonary': '#2b3950',
  '--bg-color-novenary': '#364762',
  '--bg-color-suggestion': '#16202c',
  '--bg-color-vim-editor': '#16202c',
  '--bg-color-switch': '#1f2c3a',
  '--bg-color-default': '#253244',
  '--text-color': '#e3ebf6',
  '--text-color-secondary': '#a5b3c5',
  '--text-color-secondary-light': '#a5b3c5',
  '--text-color-tertiary': '#8394a8',
  '--text-color-quaternary': '#6c7d90',
  '--border-color': '#223145',
  '--border-color-light': '#31445f',
  '--splitter-color': '#223145',
  '--globalInput-bg-color': '#1d2937',
  '--button-bg-color': '#5b8fff',
  '--button-default-bg-color': '#253244',
  '--input-number-bg': '#1d2937',
  '--input-number-hover-bg': '#253244',
  '--select-bg': '#1d2937',
  '--select-hover-bg': '#253244',
  '--select-border': '#31445f',
  '--card-bg': '#18222e',
  '--card-border': '#2a3850',
  '--command-output-bg': '#16202c',
  '--input-focus-border': '#7aa6ff',
  '--button-hover-bg': '#7aa6ff',
  '--button-active-bg': '#3f74e8',
  '--info-color': '#5b8fff',
  '--scrollbar-track-color': '#16202c',
  '--scrollbar-thumb-color': '#3a4d65',
  '--scrollbar-thumb-hover-color': '#4a607c'
})

const TERMIUS_LIGHT_UI = withUiOverrides(TERMIUS_LIGHT_TERM, 'light', {
  '--bg-color': '#f4f7fb',
  '--bg-color-secondary': '#ffffff',
  '--bg-color-tertiary': '#edf2f8',
  '--bg-color-quaternary': '#e1e8f3',
  '--bg-color-quinary': '#edf3f9',
  '--bg-color-senary': '#f8fbff',
  '--bg-color-septenary': '#eef5ff',
  '--bg-color-octonary': '#dbe4f0',
  '--bg-color-novenary': '#ced8e6',
  '--bg-color-suggestion': '#f8fbff',
  '--bg-color-vim-editor': '#ffffff',
  '--bg-color-switch': '#dae3ee',
  '--bg-color-default': '#e1e8f3',
  '--text-color': '#1d2835',
  '--text-color-secondary': '#617385',
  '--text-color-secondary-light': '#617385',
  '--text-color-tertiary': '#7b8c9d',
  '--text-color-quaternary': '#93a2b2',
  '--border-color': '#d8e0eb',
  '--border-color-light': '#cdd7e4',
  '--splitter-color': '#d8e0eb',
  '--globalInput-bg-color': '#edf3f9',
  '--button-bg-color': '#3d74f2',
  '--button-default-bg-color': '#e1e8f3',
  '--input-number-bg': '#edf3f9',
  '--input-number-hover-bg': '#e1e8f3',
  '--select-bg': '#edf3f9',
  '--select-hover-bg': '#e1e8f3',
  '--select-border': '#cdd7e4',
  '--card-bg': '#ffffff',
  '--card-border': '#dde4ee',
  '--command-output-bg': '#f8fbff',
  '--input-focus-border': '#5a85f5',
  '--button-hover-bg': '#5a85f5',
  '--button-active-bg': '#2f62d8',
  '--info-color': '#3d74f2',
  '--scrollbar-track-color': '#edf2f8',
  '--scrollbar-thumb-color': '#b7c2d1',
  '--scrollbar-thumb-hover-color': '#a4b0c0'
})

const FLEXOKI_DARK_UI = withUiOverrides(FLEXOKI_DARK_TERM, 'dark', {
  '--bg-color': '#130f0c',
  '--bg-color-secondary': '#191410',
  '--bg-color-tertiary': '#211b16',
  '--bg-color-quaternary': '#2b231d',
  '--bg-color-quinary': '#241c16',
  '--bg-color-senary': '#1c1612',
  '--bg-color-septenary': '#1d1712',
  '--bg-color-octonary': '#352b24',
  '--bg-color-novenary': '#44372f',
  '--bg-color-suggestion': '#191410',
  '--bg-color-vim-editor': '#191410',
  '--bg-color-switch': '#241c16',
  '--bg-color-default': '#2b231d',
  '--text-color': '#ddd2bf',
  '--text-color-secondary': '#b6a18b',
  '--text-color-secondary-light': '#b6a18b',
  '--text-color-tertiary': '#95806c',
  '--text-color-quaternary': '#7d6958',
  '--border-color': '#38291f',
  '--border-color-light': '#4a372b',
  '--splitter-color': '#38291f',
  '--globalInput-bg-color': '#241c16',
  '--button-bg-color': '#b06a2f',
  '--button-default-bg-color': '#2b231d',
  '--input-number-bg': '#241c16',
  '--input-number-hover-bg': '#2b231d',
  '--select-bg': '#241c16',
  '--select-hover-bg': '#2b231d',
  '--select-border': '#4a372b',
  '--card-bg': '#1c1612',
  '--card-border': '#392c23',
  '--command-output-bg': '#191410',
  '--input-focus-border': '#c98852',
  '--button-hover-bg': '#c98852',
  '--button-active-bg': '#8b4f1f',
  '--info-color': '#b06a2f',
  '--scrollbar-track-color': '#191410',
  '--scrollbar-thumb-color': '#514036',
  '--scrollbar-thumb-hover-color': '#665144'
})

const FLEXOKI_LIGHT_UI = withUiOverrides(FLEXOKI_LIGHT_TERM, 'light', {
  '--bg-color': '#f7efdf',
  '--bg-color-secondary': '#fdf7ea',
  '--bg-color-tertiary': '#f1e7d3',
  '--bg-color-quaternary': '#e5d7be',
  '--bg-color-quinary': '#f3ead8',
  '--bg-color-senary': '#fdf7ea',
  '--bg-color-septenary': '#f4ead8',
  '--bg-color-octonary': '#dbcdb4',
  '--bg-color-novenary': '#cdbda6',
  '--bg-color-suggestion': '#fdf7ea',
  '--bg-color-vim-editor': '#fdf7ea',
  '--bg-color-switch': '#e5d7be',
  '--bg-color-default': '#e5d7be',
  '--text-color': '#372e25',
  '--text-color-secondary': '#80705f',
  '--text-color-secondary-light': '#80705f',
  '--text-color-tertiary': '#998978',
  '--text-color-quaternary': '#ad9a87',
  '--border-color': '#dccbb5',
  '--border-color-light': '#d0bea9',
  '--splitter-color': '#dccbb5',
  '--globalInput-bg-color': '#f3ead8',
  '--button-bg-color': '#b37a33',
  '--button-default-bg-color': '#e5d7be',
  '--input-number-bg': '#f3ead8',
  '--input-number-hover-bg': '#e5d7be',
  '--select-bg': '#f3ead8',
  '--select-hover-bg': '#e5d7be',
  '--select-border': '#d0bea9',
  '--card-bg': '#fdf7ea',
  '--card-border': '#e2d2bc',
  '--command-output-bg': '#fdf7ea',
  '--input-focus-border': '#c88d46',
  '--button-hover-bg': '#c88d46',
  '--button-active-bg': '#95631e',
  '--info-color': '#b37a33',
  '--scrollbar-track-color': '#f1e7d3',
  '--scrollbar-thumb-color': '#c5b39b',
  '--scrollbar-thumb-hover-color': '#b29e84'
})

const KANAGAWA_WAVE_UI = withUiOverrides(KANAGAWA_WAVE_TERM, 'dark', {
  '--bg-color': '#141625',
  '--bg-color-secondary': '#1a1d2f',
  '--bg-color-tertiary': '#20243a',
  '--bg-color-quaternary': '#2a3047',
  '--bg-color-quinary': '#232842',
  '--bg-color-senary': '#1c2032',
  '--bg-color-septenary': '#1b2137',
  '--bg-color-octonary': '#343b56',
  '--bg-color-novenary': '#424b69',
  '--bg-color-suggestion': '#1a1d2f',
  '--bg-color-vim-editor': '#1a1d2f',
  '--bg-color-switch': '#242947',
  '--bg-color-default': '#2a3047',
  '--text-color': '#d8d5c2',
  '--text-color-secondary': '#9f9cb0',
  '--text-color-secondary-light': '#9f9cb0',
  '--text-color-tertiary': '#838099',
  '--text-color-quaternary': '#6d6a84',
  '--border-color': '#2a2f49',
  '--border-color-light': '#394067',
  '--splitter-color': '#2a2f49',
  '--globalInput-bg-color': '#232842',
  '--button-bg-color': '#86a2ff',
  '--button-default-bg-color': '#2a3047',
  '--input-number-bg': '#232842',
  '--input-number-hover-bg': '#2a3047',
  '--select-bg': '#232842',
  '--select-hover-bg': '#2a3047',
  '--select-border': '#394067',
  '--card-bg': '#1c2032',
  '--card-border': '#313857',
  '--command-output-bg': '#1a1d2f',
  '--input-focus-border': '#9db6ff',
  '--button-hover-bg': '#9db6ff',
  '--button-active-bg': '#607bcc',
  '--info-color': '#86a2ff',
  '--scrollbar-track-color': '#1a1d2f',
  '--scrollbar-thumb-color': '#454d6b',
  '--scrollbar-thumb-hover-color': '#5a6488'
})

const KANAGAWA_DRAGON_UI = withUiOverrides(KANAGAWA_DRAGON_TERM, 'dark', {
  '--bg-color': '#18110f',
  '--bg-color-secondary': '#221715',
  '--bg-color-tertiary': '#2b1f1d',
  '--bg-color-quaternary': '#372825',
  '--bg-color-quinary': '#2d211e',
  '--bg-color-senary': '#251a18',
  '--bg-color-septenary': '#261a18',
  '--bg-color-octonary': '#43302d',
  '--bg-color-novenary': '#533c38',
  '--bg-color-suggestion': '#221715',
  '--bg-color-vim-editor': '#221715',
  '--bg-color-switch': '#2c201d',
  '--bg-color-default': '#372825',
  '--text-color': '#dbc9c2',
  '--text-color-secondary': '#b79c93',
  '--text-color-secondary-light': '#b79c93',
  '--text-color-tertiary': '#967b73',
  '--text-color-quaternary': '#7c645d',
  '--border-color': '#472c28',
  '--border-color-light': '#5b3935',
  '--splitter-color': '#472c28',
  '--globalInput-bg-color': '#2d211e',
  '--button-bg-color': '#c17563',
  '--button-default-bg-color': '#372825',
  '--input-number-bg': '#2d211e',
  '--input-number-hover-bg': '#372825',
  '--select-bg': '#2d211e',
  '--select-hover-bg': '#372825',
  '--select-border': '#5b3935',
  '--card-bg': '#251a18',
  '--card-border': '#442b28',
  '--command-output-bg': '#221715',
  '--input-focus-border': '#d08a79',
  '--button-hover-bg': '#d08a79',
  '--button-active-bg': '#9c5748',
  '--info-color': '#c17563',
  '--scrollbar-track-color': '#221715',
  '--scrollbar-thumb-color': '#5a403c',
  '--scrollbar-thumb-hover-color': '#704f4a'
})

const KANAGAWA_LOTUS_UI = withUiOverrides(KANAGAWA_LOTUS_TERM, 'light', {
  '--bg-color': '#fff2ec',
  '--bg-color-secondary': '#fff8f5',
  '--bg-color-tertiary': '#fde7e5',
  '--bg-color-quaternary': '#efd6d9',
  '--bg-color-quinary': '#fbeceb',
  '--bg-color-senary': '#fff8f7',
  '--bg-color-septenary': '#fce9ea',
  '--bg-color-octonary': '#e6cad2',
  '--bg-color-novenary': '#d8bbc6',
  '--bg-color-suggestion': '#fff8f5',
  '--bg-color-vim-editor': '#fff8f5',
  '--bg-color-switch': '#efd6d9',
  '--bg-color-default': '#efd6d9',
  '--text-color': '#625565',
  '--text-color-secondary': '#8a788b',
  '--text-color-secondary-light': '#8a788b',
  '--text-color-tertiary': '#a392a4',
  '--text-color-quaternary': '#b5a6b6',
  '--border-color': '#e6d2d6',
  '--border-color-light': '#d9c2c8',
  '--splitter-color': '#e6d2d6',
  '--globalInput-bg-color': '#fbeceb',
  '--button-bg-color': '#b47edc',
  '--button-default-bg-color': '#efd6d9',
  '--input-number-bg': '#fbeceb',
  '--input-number-hover-bg': '#efd6d9',
  '--select-bg': '#fbeceb',
  '--select-hover-bg': '#efd6d9',
  '--select-border': '#d9c2c8',
  '--card-bg': '#fff8f7',
  '--card-border': '#e8d3d8',
  '--command-output-bg': '#fff8f5',
  '--input-focus-border': '#c694ec',
  '--button-hover-bg': '#c694ec',
  '--button-active-bg': '#8c5eb3',
  '--info-color': '#b47edc',
  '--scrollbar-track-color': '#fde7e5',
  '--scrollbar-thumb-color': '#cbb1bb',
  '--scrollbar-thumb-hover-color': '#bc9fa9'
})

const HACKER_BLUE_UI = withUiOverrides(HACKER_BLUE_TERM, 'dark', {
  '--bg-color': '#090d12',
  '--bg-color-secondary': '#0d131b',
  '--bg-color-tertiary': '#111a25',
  '--bg-color-quaternary': '#162334',
  '--bg-color-quinary': '#122031',
  '--bg-color-senary': '#0f1721',
  '--bg-color-septenary': '#101a28',
  '--bg-color-octonary': '#1b2b41',
  '--bg-color-novenary': '#223652',
  '--bg-color-suggestion': '#0d131b',
  '--bg-color-vim-editor': '#0d131b',
  '--bg-color-switch': '#132132',
  '--bg-color-default': '#162334',
  '--text-color': '#d2e7ff',
  '--text-color-secondary': '#89a7c8',
  '--text-color-secondary-light': '#89a7c8',
  '--text-color-tertiary': '#6785a7',
  '--text-color-quaternary': '#537091',
  '--border-color': '#17304e',
  '--border-color-light': '#214166',
  '--splitter-color': '#17304e',
  '--globalInput-bg-color': '#122031',
  '--button-bg-color': '#3f8cff',
  '--button-default-bg-color': '#162334',
  '--input-number-bg': '#122031',
  '--input-number-hover-bg': '#162334',
  '--select-bg': '#122031',
  '--select-hover-bg': '#162334',
  '--select-border': '#214166',
  '--card-bg': '#0f1721',
  '--card-border': '#1a2e47',
  '--command-output-bg': '#0d131b',
  '--input-focus-border': '#64a5ff',
  '--button-hover-bg': '#64a5ff',
  '--button-active-bg': '#2b70d6',
  '--info-color': '#3f8cff',
  '--scrollbar-track-color': '#0d131b',
  '--scrollbar-thumb-color': '#28415f',
  '--scrollbar-thumb-hover-color': '#34557c'
})

const HACKER_GREEN_UI = withUiOverrides(HACKER_GREEN_TERM, 'dark', {
  '--bg-color': '#090f0c',
  '--bg-color-secondary': '#0d1511',
  '--bg-color-tertiary': '#11201a',
  '--bg-color-quaternary': '#173027',
  '--bg-color-quinary': '#12261d',
  '--bg-color-senary': '#0f1c16',
  '--bg-color-septenary': '#102219',
  '--bg-color-octonary': '#1c3b2f',
  '--bg-color-novenary': '#244a3b',
  '--bg-color-suggestion': '#0d1511',
  '--bg-color-vim-editor': '#0d1511',
  '--bg-color-switch': '#13271d',
  '--bg-color-default': '#173027',
  '--text-color': '#d8f3df',
  '--text-color-secondary': '#8daf97',
  '--text-color-secondary-light': '#8daf97',
  '--text-color-tertiary': '#6f9179',
  '--text-color-quaternary': '#5a7563',
  '--border-color': '#153125',
  '--border-color-light': '#1f4333',
  '--splitter-color': '#153125',
  '--globalInput-bg-color': '#12261d',
  '--button-bg-color': '#46c978',
  '--button-default-bg-color': '#173027',
  '--input-number-bg': '#12261d',
  '--input-number-hover-bg': '#173027',
  '--select-bg': '#12261d',
  '--select-hover-bg': '#173027',
  '--select-border': '#1f4333',
  '--card-bg': '#0f1c16',
  '--card-border': '#183428',
  '--command-output-bg': '#0d1511',
  '--input-focus-border': '#68d98d',
  '--button-hover-bg': '#68d98d',
  '--button-active-bg': '#30ad61',
  '--info-color': '#46c978',
  '--scrollbar-track-color': '#0d1511',
  '--scrollbar-thumb-color': '#28503d',
  '--scrollbar-thumb-hover-color': '#34664e'
})

const DRACULA_NIGHT_UI = withUiOverrides(DRACULA_NIGHT_TERM, 'dark', {
  '--bg-color': '#1f1f2c',
  '--bg-color-secondary': '#262737',
  '--bg-color-tertiary': '#2d2f42',
  '--bg-color-quaternary': '#393c54',
  '--bg-color-quinary': '#312f46',
  '--bg-color-senary': '#29293b',
  '--bg-color-septenary': '#2a2c40',
  '--bg-color-octonary': '#474a65',
  '--bg-color-novenary': '#565a79',
  '--bg-color-suggestion': '#262737',
  '--bg-color-vim-editor': '#262737',
  '--bg-color-switch': '#34344b',
  '--bg-color-default': '#393c54',
  '--text-color': '#f6f3ff',
  '--text-color-secondary': '#c3bdd7',
  '--text-color-secondary-light': '#c3bdd7',
  '--text-color-tertiary': '#a39cb8',
  '--text-color-quaternary': '#8882a0',
  '--border-color': '#3a3554',
  '--border-color-light': '#504a73',
  '--splitter-color': '#3a3554',
  '--globalInput-bg-color': '#312f46',
  '--button-bg-color': '#bd93f9',
  '--button-default-bg-color': '#393c54',
  '--input-number-bg': '#312f46',
  '--input-number-hover-bg': '#393c54',
  '--select-bg': '#312f46',
  '--select-hover-bg': '#393c54',
  '--select-border': '#504a73',
  '--card-bg': '#29293b',
  '--card-border': '#413c5e',
  '--command-output-bg': '#262737',
  '--input-focus-border': '#d1b3ff',
  '--button-hover-bg': '#d1b3ff',
  '--button-active-bg': '#936fd1',
  '--info-color': '#bd93f9',
  '--scrollbar-track-color': '#262737',
  '--scrollbar-thumb-color': '#55506f',
  '--scrollbar-thumb-hover-color': '#6b648a'
})

const CATPPUCCIN_MOCHA_UI = withUiOverrides(CATPPUCCIN_MOCHA_TERM, 'dark', {
  '--bg-color': '#181825',
  '--bg-color-secondary': '#1f2030',
  '--bg-color-tertiary': '#26283b',
  '--bg-color-quaternary': '#313449',
  '--bg-color-quinary': '#292b40',
  '--bg-color-senary': '#222335',
  '--bg-color-septenary': '#24263a',
  '--bg-color-octonary': '#3b3f57',
  '--bg-color-novenary': '#4a4f6b',
  '--bg-color-suggestion': '#1f2030',
  '--bg-color-vim-editor': '#1f2030',
  '--bg-color-switch': '#2b2d43',
  '--bg-color-default': '#313449',
  '--text-color': '#d9e0f6',
  '--text-color-secondary': '#b2bbdb',
  '--text-color-secondary-light': '#b2bbdb',
  '--text-color-tertiary': '#939cc1',
  '--text-color-quaternary': '#7e87ad',
  '--border-color': '#31354f',
  '--border-color-light': '#474c67',
  '--splitter-color': '#31354f',
  '--globalInput-bg-color': '#292b40',
  '--button-bg-color': '#8caaee',
  '--button-default-bg-color': '#313449',
  '--input-number-bg': '#292b40',
  '--input-number-hover-bg': '#313449',
  '--select-bg': '#292b40',
  '--select-hover-bg': '#313449',
  '--select-border': '#474c67',
  '--card-bg': '#222335',
  '--card-border': '#343950',
  '--command-output-bg': '#1f2030',
  '--input-focus-border': '#a6c1ff',
  '--button-hover-bg': '#a6c1ff',
  '--button-active-bg': '#6789d8',
  '--info-color': '#8caaee',
  '--scrollbar-track-color': '#1f2030',
  '--scrollbar-thumb-color': '#535871',
  '--scrollbar-thumb-hover-color': '#686f8d'
})

const CATPPUCCIN_LATTE_UI = withUiOverrides(CATPPUCCIN_LATTE_TERM, 'light', {
  '--bg-color': '#f2f0f8',
  '--bg-color-secondary': '#fcfafc',
  '--bg-color-tertiary': '#ebe8f3',
  '--bg-color-quaternary': '#ddd9e8',
  '--bg-color-quinary': '#f0ebf7',
  '--bg-color-senary': '#f8f4fb',
  '--bg-color-septenary': '#efeaf6',
  '--bg-color-octonary': '#d4cfe2',
  '--bg-color-novenary': '#c6c0d8',
  '--bg-color-suggestion': '#fcfafc',
  '--bg-color-vim-editor': '#fcfafc',
  '--bg-color-switch': '#ddd7e9',
  '--bg-color-default': '#ddd9e8',
  '--text-color': '#4c4f69',
  '--text-color-secondary': '#6d6f89',
  '--text-color-secondary-light': '#6d6f89',
  '--text-color-tertiary': '#8f90a5',
  '--text-color-quaternary': '#a8a7b7',
  '--border-color': '#d9d3e5',
  '--border-color-light': '#cbc5dc',
  '--splitter-color': '#d9d3e5',
  '--globalInput-bg-color': '#f0ebf7',
  '--button-bg-color': '#8c6be8',
  '--button-default-bg-color': '#ddd9e8',
  '--input-number-bg': '#f0ebf7',
  '--input-number-hover-bg': '#ddd9e8',
  '--select-bg': '#f0ebf7',
  '--select-hover-bg': '#ddd9e8',
  '--select-border': '#cbc5dc',
  '--card-bg': '#f8f4fb',
  '--card-border': '#d8d1e3',
  '--command-output-bg': '#fcfafc',
  '--input-focus-border': '#a68aff',
  '--button-hover-bg': '#a68aff',
  '--button-active-bg': '#7050cf',
  '--info-color': '#8c6be8',
  '--scrollbar-track-color': '#ebe8f3',
  '--scrollbar-thumb-color': '#c4bdd3',
  '--scrollbar-thumb-hover-color': '#b0a7c3'
})

const GRUVBOX_DARK_UI = withUiOverrides(GRUVBOX_DARK_TERM, 'dark', {
  '--bg-color': '#171611',
  '--bg-color-secondary': '#1f1d18',
  '--bg-color-tertiary': '#28251f',
  '--bg-color-quaternary': '#343128',
  '--bg-color-quinary': '#2b2821',
  '--bg-color-senary': '#23211b',
  '--bg-color-septenary': '#24231c',
  '--bg-color-octonary': '#403c32',
  '--bg-color-novenary': '#514c40',
  '--bg-color-suggestion': '#1f1d18',
  '--bg-color-vim-editor': '#1f1d18',
  '--bg-color-switch': '#2e2a23',
  '--bg-color-default': '#343128',
  '--text-color': '#dbd6bb',
  '--text-color-secondary': '#b1a88a',
  '--text-color-secondary-light': '#b1a88a',
  '--text-color-tertiary': '#938a6d',
  '--text-color-quaternary': '#7a7159',
  '--border-color': '#383527',
  '--border-color-light': '#4b4738',
  '--splitter-color': '#383527',
  '--globalInput-bg-color': '#2b2821',
  '--button-bg-color': '#98a84d',
  '--button-default-bg-color': '#343128',
  '--input-number-bg': '#2b2821',
  '--input-number-hover-bg': '#343128',
  '--select-bg': '#2b2821',
  '--select-hover-bg': '#343128',
  '--select-border': '#4b4738',
  '--card-bg': '#23211b',
  '--card-border': '#3a372c',
  '--command-output-bg': '#1f1d18',
  '--input-focus-border': '#b2c362',
  '--button-hover-bg': '#b2c362',
  '--button-active-bg': '#748433',
  '--info-color': '#98a84d',
  '--scrollbar-track-color': '#1f1d18',
  '--scrollbar-thumb-color': '#555041',
  '--scrollbar-thumb-hover-color': '#6b6554'
})

const NORD_FROST_UI = withUiOverrides(NORD_FROST_TERM, 'dark', {
  '--bg-color': '#242a35',
  '--bg-color-secondary': '#2b3240',
  '--bg-color-tertiary': '#323a4a',
  '--bg-color-quaternary': '#3e475b',
  '--bg-color-quinary': '#363f52',
  '--bg-color-senary': '#2e3645',
  '--bg-color-septenary': '#303949',
  '--bg-color-octonary': '#4c566d',
  '--bg-color-novenary': '#5d687f',
  '--bg-color-suggestion': '#2b3240',
  '--bg-color-vim-editor': '#2b3240',
  '--bg-color-switch': '#394155',
  '--bg-color-default': '#3e475b',
  '--text-color': '#e4ebf5',
  '--text-color-secondary': '#b7c4d5',
  '--text-color-secondary-light': '#b7c4d5',
  '--text-color-tertiary': '#95a5b9',
  '--text-color-quaternary': '#7d8ea4',
  '--border-color': '#3b465a',
  '--border-color-light': '#516077',
  '--splitter-color': '#3b465a',
  '--globalInput-bg-color': '#363f52',
  '--button-bg-color': '#7fa7d8',
  '--button-default-bg-color': '#3e475b',
  '--input-number-bg': '#363f52',
  '--input-number-hover-bg': '#3e475b',
  '--select-bg': '#363f52',
  '--select-hover-bg': '#3e475b',
  '--select-border': '#516077',
  '--card-bg': '#2e3645',
  '--card-border': '#415066',
  '--command-output-bg': '#2b3240',
  '--input-focus-border': '#9fc0ea',
  '--button-hover-bg': '#9fc0ea',
  '--button-active-bg': '#5e86b7',
  '--info-color': '#7fa7d8',
  '--scrollbar-track-color': '#2b3240',
  '--scrollbar-thumb-color': '#5a6a7f',
  '--scrollbar-thumb-hover-color': '#70849b'
})

export const THEME_PRESETS: Record<ConcreteThemeId, ThemePreset> = {
  dark: preset('dark', 'Dark', 'dark', DARK_TERM, LEGACY_DARK_UI, { color: '#141414', symbolColor: '#ffffff' }),
  light: preset('light', 'Light', 'light', LIGHT_TERM, LEGACY_LIGHT_UI, { color: '#ffffff', symbolColor: '#141414' }),

  'termius-dark': preset('termius-dark', 'Graphite Dark', 'dark', TERMIUS_DARK_TERM, TERMIUS_DARK_UI, { color: '#111417', symbolColor: '#D9DBDE' }),
  'termius-light': preset('termius-light', 'Mist Light', 'light', TERMIUS_LIGHT_TERM, TERMIUS_LIGHT_UI, { color: '#FFFFFF', symbolColor: '#2A2F33' }),

  'flexoki-dark': preset('flexoki-dark', 'Ember Earth', 'dark', FLEXOKI_DARK_TERM, FLEXOKI_DARK_UI, { color: '#100F0F', symbolColor: '#CECDC3' }),
  'flexoki-light': preset('flexoki-light', 'Canvas Paper', 'light', FLEXOKI_LIGHT_TERM, FLEXOKI_LIGHT_UI, {
    color: '#FFFCF0',
    symbolColor: '#100F0F'
  }),

  'kanagawa-wave': preset('kanagawa-wave', 'Tide Indigo', 'dark', KANAGAWA_WAVE_TERM, KANAGAWA_WAVE_UI, { color: '#1F1F28', symbolColor: '#DCD7BA' }),
  'kanagawa-dragon': preset('kanagawa-dragon', 'Forge Copper', 'dark', KANAGAWA_DRAGON_TERM, KANAGAWA_DRAGON_UI, {
    color: '#181616',
    symbolColor: '#C5C9C5'
  }),
  'kanagawa-lotus': preset('kanagawa-lotus', 'Dawn Petal', 'light', KANAGAWA_LOTUS_TERM, KANAGAWA_LOTUS_UI, {
    color: '#F2ECBC',
    symbolColor: '#545464'
  }),

  'hacker-blue': preset('hacker-blue', 'Pulse Blue', 'dark', HACKER_BLUE_TERM, HACKER_BLUE_UI, { color: '#000000', symbolColor: '#4D9FFF' }),
  'hacker-green': preset('hacker-green', 'Pulse Green', 'dark', HACKER_GREEN_TERM, HACKER_GREEN_UI, { color: '#000000', symbolColor: '#00FF00' }),
  'dracula-night': preset('dracula-night', 'Eclipse Violet', 'dark', DRACULA_NIGHT_TERM, DRACULA_NIGHT_UI, {
    color: '#282A36',
    symbolColor: '#F8F8F2'
  }),
  'catppuccin-mocha': preset('catppuccin-mocha', 'Truffle Mocha', 'dark', CATPPUCCIN_MOCHA_TERM, CATPPUCCIN_MOCHA_UI, {
    color: '#1E1E2E',
    symbolColor: '#CDD6F4'
  }),
  'catppuccin-latte': preset('catppuccin-latte', 'Cream Latte', 'light', CATPPUCCIN_LATTE_TERM, CATPPUCCIN_LATTE_UI, {
    color: '#EFF1F5',
    symbolColor: '#4C4F69'
  }),
  'gruvbox-dark': preset('gruvbox-dark', 'Grove Moss', 'dark', GRUVBOX_DARK_TERM, GRUVBOX_DARK_UI, { color: '#282828', symbolColor: '#EBDBB2' }),
  'nord-frost': preset('nord-frost', 'Fjord Ice', 'dark', NORD_FROST_TERM, NORD_FROST_UI, { color: '#2E3440', symbolColor: '#D8DEE9' })
}
