// Shared DB-AI types used across main / preload / renderer processes.
// All three processes MUST import from this single source of truth to avoid
// type drift between IPC producers and consumers. See docs/database_ai.md
// §5.1 - §5.3 for the full protocol description.

/**
 * Supported database engines for DB-AI single-turn actions (track A).
 * DB ChatBot (track B) uses the same literal union; keep in sync if extended.
 */
export type DbType = 'mysql' | 'postgresql'

/**
 * Supported SQL dialects for prompt construction and target-dialect conversion.
 * The current MVP targets PostgreSQL and MySQL only; additional dialects should
 * be appended to this union (never renamed) to preserve IPC payload stability.
 */
export type SqlDialect = 'mysql' | 'postgresql'

/**
 * Single-turn DB-AI actions. `chat` is deliberately NOT part of this union:
 * multi-turn conversations go through the Task/Controller pipeline
 * (workspace='database') on track B. See docs/database_ai.md §5.0.
 */
export type DbAiAction = 'nl2sql' | 'explain' | 'optimize' | 'convert' | 'complete' | 'diagnose'

/**
 * Hint describing a table the user or caller explicitly references.
 * `schema` is optional because MySQL sessions typically rely on the current
 * database, whereas PostgreSQL relies on schema + search_path.
 */
export interface DbAiTableHint {
  schema?: string
  table: string
}

/**
 * Connection and scoping context shared by every DB-AI request.
 * `assetId` MUST match an already-connected asset known to ConnectionManager;
 * the main-side handler rejects the request otherwise.
 */
export interface DbAiRequestContext {
  assetId: string
  databaseName?: string
  schemaName?: string
  tableName?: string
  dbType: DbType
}

/**
 * Structured input for a single DB-AI action. Fields are optional because
 * different actions consume different shapes (e.g. `nl2sql` uses `question`,
 * `explain`/`optimize` use `sql`, `complete` uses cursor context).
 * Payload size limits are enforced by the main-process handler (§5.3).
 */
export interface DbAiStartInput {
  sql?: string
  question?: string
  selectedText?: string
  cursorTextBefore?: string
  cursorTextAfter?: string
  targetDialect?: SqlDialect
  hintedTables?: DbAiTableHint[]
  /** Error message from a failed SQL execution, used by the 'diagnose' action. */
  errorMessage?: string
}

/**
 * Per-request options. `modelOverride` allows the UI to pin a specific model
 * for a one-off call; `maxSchemaTokens` caps schema-context injection; `dryRun`
 * skips the provider call and is intended for diagnostics/E2E tests only.
 */
export interface DbAiStartOptions {
  modelOverride?: string
  maxSchemaTokens?: number
  dryRun?: boolean
}

/**
 * Full DB-AI start request payload. `reqId` is generated by the renderer
 * (UUID) BEFORE `start()` is invoked so that event listeners can be registered
 * ahead of the first stream event.
 */
export interface DbAiStartRequest {
  reqId: string
  action: DbAiAction
  context: DbAiRequestContext
  input: DbAiStartInput
  options?: DbAiStartOptions
}

/**
 * Result of `dbAi.start(req)`. The handler returns synchronously after basic
 * validation; the actual model output arrives via stream/tool/done events.
 */
export type DbAiStartResult = { ok: true; reqId: string } | { ok: false; errorMessage: string }

/**
 * Result of `dbAi.cancel(reqId)`. Cancel is best-effort on MVP: returning
 * `{ ok: true }` only guarantees that downstream IPC is stopped.
 */
export interface DbAiCancelResult {
  ok: boolean
}

/**
 * Streaming text/reasoning chunk from the model. `reasoning` chunks are emitted
 * by providers that expose a separate reasoning channel (e.g. Anthropic
 * extended thinking); renderer renders them in a collapsed section.
 */
export interface DbAiStreamEvent {
  reqId: string
  action: DbAiAction
  kind: 'text' | 'reasoning'
  text: string
}

/**
 * Lifecycle of a tool invocation surfaced to the renderer. Used by single-turn
 * actions that fetch schema context. Preview fields are pre-truncated by the
 * service layer and MUST NOT contain raw SQL or credentials.
 */
export interface DbAiToolEvent {
  reqId: string
  toolName: string
  status: 'started' | 'finished' | 'error'
  inputPreview?: string
  outputPreview?: string
  rowCount?: number
  durationMs?: number
  errorMessage?: string
}

/**
 * Final event for a request. `ok=false` indicates a terminal error and
 * `errorMessage` is guaranteed to be sanitized (no host/credential/SQL).
 */
export interface DbAiDoneEvent {
  reqId: string
  action: DbAiAction
  ok: boolean
  errorMessage?: string
  usage?: {
    inputTokens?: number
    outputTokens?: number
    totalCost?: number
  }
  result?: {
    text?: string
    sql?: string
    tablesUsed?: DbAiTableHint[]
  }
}

/**
 * Preload surface exposed on `window.api.dbAi`. Subscription callbacks return
 * an unsubscribe function; renderer MUST unsubscribe on component unmount to
 * avoid leaks across navigations.
 */
export interface DbAiApi {
  start(req: DbAiStartRequest): Promise<DbAiStartResult>
  cancel(reqId: string): Promise<DbAiCancelResult>
  onStream(cb: (event: DbAiStreamEvent) => void): () => void
  onTool(cb: (event: DbAiToolEvent) => void): () => void
  onDone(cb: (event: DbAiDoneEvent) => void): () => void
}

/**
 * IPC channel names. Centralized here so that main / preload reference the
 * same string literals; renaming any of these is a breaking change.
 */
export const DB_AI_IPC_CHANNELS = {
  start: 'db-ai:start',
  cancel: 'db-ai:cancel',
  stream: 'db-ai:stream',
  tool: 'db-ai:tool',
  done: 'db-ai:done'
} as const

export type DbAiIpcChannel = (typeof DB_AI_IPC_CHANNELS)[keyof typeof DB_AI_IPC_CHANNELS]

// ---------------------------------------------------------------------------
// Renderer-side view state shared by the drawer + store. These types are NOT
// part of the IPC payload (main never constructs them); they live here purely
// to give every renderer consumer a single import source. See docs/database_ai.md
// §11.3 for the store contract.
// ---------------------------------------------------------------------------

/**
 * Lifecycle of a single DB-AI request as seen by the drawer. `queued` is the
 * brief window between renderer calling `start()` and the first stream chunk
 * arriving; `streaming` flips on the first chunk; terminal states are
 * `done` / `error` / `cancelled`.
 */
export type DbAiRequestStatus = 'queued' | 'streaming' | 'done' | 'error' | 'cancelled'

/**
 * Full renderer-side state for a single DB-AI request. Stored under
 * `databaseWorkspaceStore.dbAi.requests[reqId]`.
 */
export interface DbAiRequestState {
  reqId: string
  action: DbAiAction
  status: DbAiRequestStatus
  context: DbAiRequestContext
  /** Accumulated text chunks. */
  text: string
  /** Accumulated reasoning chunks (may be empty when provider exposes none). */
  reasoningText: string
  /** Extracted SQL block from the model output; populated by the done event. */
  sql?: string
  errorMessage?: string
  /** Target dialect captured at request-start so the drawer can label it. */
  targetDialect?: SqlDialect
  createdAt: number
  updatedAt: number
}

/**
 * Aggregated DB-AI slice of the workspace store. Only single-turn (track A)
 * state lives here; multi-turn ChatBot (track B) state is owned by the
 * Task/Controller layer.
 *
 * Layout fields (`aiPaneOpen` / `sidebarSize`) control the Database
 * workspace's optional third pane that hosts AiTab in MVP-B. They are
 * independent of `requests` / `drawerOpen` (those drive the single-turn
 * drawer). See docs/db-ai-aitab-mount-decision.md (Q1 / Q5).
 */
export interface DbAiStoreState {
  modelOverride?: string
  requests: Record<string, DbAiRequestState>
  activeReqId: string | null
  drawerOpen: boolean
  /**
   * Whether the Database workspace's AI pane is currently visible. Toggled
   * by the DatabaseWorkspaceTabs AI button. Defaults to `false` so the
   * first-time user sees the classic two-pane layout.
   */
  aiPaneOpen: boolean
  /**
   * Persisted size (px) of the AI pane when open. Defaults to 360. Kept
   * as a raw pixel value for predictability across different viewport
   * widths; splitpanes converts to percentage at render time.
   */
  sidebarSize: number
}
