/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const AModal: typeof import('ant-design-vue/es').Modal
  const createRendererLogger: typeof import('@/utils/logger').createRendererLogger
}
